### ISSUE TITLE
Check code quality for features implemented by WJ

### ISSUE THREAD

**Issue by WeiJie96** [AY2021S1-CS2103-T16-2/tp#158]
- [ ] Defensive coding (if applicable)
- [ ] Coding Standard
- [ ] SLAP => long methods / deep nesting
- [ ] Code duplications e.g. in test code
- [ ] Others
